package projetofinal;

public class calculadora extends javax.swing.JFrame {

    public calculadora() {
        initComponents();
    }

    double valor1, valor2, resultado;
    String operacao;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfTela = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbtbackspace = new javax.swing.JButton();
        jbtquadrado = new javax.swing.JButton();
        jbtlimpatela = new javax.swing.JButton();
        jbtdivisao = new javax.swing.JButton();
        jbt7 = new javax.swing.JButton();
        jbt8 = new javax.swing.JButton();
        jbt9 = new javax.swing.JButton();
        jbtmultiplicacao = new javax.swing.JButton();
        jbt4 = new javax.swing.JButton();
        jbt5 = new javax.swing.JButton();
        jbt6 = new javax.swing.JButton();
        jbtsubtracao = new javax.swing.JButton();
        jbt1 = new javax.swing.JButton();
        jbt2 = new javax.swing.JButton();
        jbt3 = new javax.swing.JButton();
        jbtadicao = new javax.swing.JButton();
        jbtsinal = new javax.swing.JButton();
        jbt0 = new javax.swing.JButton();
        jbtresultado = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jfTela.setBackground(new java.awt.Color(0, 0, 0));
        jfTela.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jfTela.setForeground(new java.awt.Color(255, 255, 255));
        jfTela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new java.awt.GridLayout(5, 4));

        jbtbackspace.setBackground(new java.awt.Color(0, 0, 0));
        jbtbackspace.setFont(new java.awt.Font("Wingdings", 0, 18)); // NOI18N
        jbtbackspace.setForeground(new java.awt.Color(255, 255, 255));
        jbtbackspace.setText("");
        jbtbackspace.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtbackspace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtbackspaceActionPerformed(evt);
            }
        });
        jPanel1.add(jbtbackspace);

        jbtquadrado.setBackground(new java.awt.Color(0, 0, 0));
        jbtquadrado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtquadrado.setForeground(new java.awt.Color(255, 255, 255));
        jbtquadrado.setText("x²");
        jbtquadrado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtquadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtquadradoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtquadrado);

        jbtlimpatela.setBackground(new java.awt.Color(0, 0, 0));
        jbtlimpatela.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtlimpatela.setForeground(new java.awt.Color(255, 255, 255));
        jbtlimpatela.setText("C");
        jbtlimpatela.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtlimpatela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtlimpatelaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtlimpatela);

        jbtdivisao.setBackground(new java.awt.Color(0, 0, 0));
        jbtdivisao.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtdivisao.setForeground(new java.awt.Color(255, 255, 255));
        jbtdivisao.setText("/");
        jbtdivisao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtdivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtdivisaoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtdivisao);

        jbt7.setBackground(new java.awt.Color(0, 0, 0));
        jbt7.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt7.setForeground(new java.awt.Color(255, 255, 255));
        jbt7.setText("7");
        jbt7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt7ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt7);

        jbt8.setBackground(new java.awt.Color(0, 0, 0));
        jbt8.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt8.setForeground(new java.awt.Color(255, 255, 255));
        jbt8.setText("8");
        jbt8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt8ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt8);

        jbt9.setBackground(new java.awt.Color(0, 0, 0));
        jbt9.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt9.setForeground(new java.awt.Color(255, 255, 255));
        jbt9.setText("9");
        jbt9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt9ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt9);

        jbtmultiplicacao.setBackground(new java.awt.Color(0, 0, 0));
        jbtmultiplicacao.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtmultiplicacao.setForeground(new java.awt.Color(255, 255, 255));
        jbtmultiplicacao.setText("*");
        jbtmultiplicacao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtmultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtmultiplicacaoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtmultiplicacao);

        jbt4.setBackground(new java.awt.Color(0, 0, 0));
        jbt4.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt4.setForeground(new java.awt.Color(255, 255, 255));
        jbt4.setText("4");
        jbt4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt4ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt4);

        jbt5.setBackground(new java.awt.Color(0, 0, 0));
        jbt5.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt5.setForeground(new java.awt.Color(255, 255, 255));
        jbt5.setText("5");
        jbt5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt5ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt5);

        jbt6.setBackground(new java.awt.Color(0, 0, 0));
        jbt6.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt6.setForeground(new java.awt.Color(255, 255, 255));
        jbt6.setText("6");
        jbt6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt6ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt6);

        jbtsubtracao.setBackground(new java.awt.Color(0, 0, 0));
        jbtsubtracao.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtsubtracao.setForeground(new java.awt.Color(255, 255, 255));
        jbtsubtracao.setText("-");
        jbtsubtracao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtsubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsubtracaoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtsubtracao);

        jbt1.setBackground(new java.awt.Color(0, 0, 0));
        jbt1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt1.setForeground(new java.awt.Color(255, 255, 255));
        jbt1.setText("1");
        jbt1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt1ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt1);

        jbt2.setBackground(new java.awt.Color(0, 0, 0));
        jbt2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt2.setForeground(new java.awt.Color(255, 255, 255));
        jbt2.setText("2");
        jbt2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt2ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt2);

        jbt3.setBackground(new java.awt.Color(0, 0, 0));
        jbt3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt3.setForeground(new java.awt.Color(255, 255, 255));
        jbt3.setText("3");
        jbt3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt3ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt3);

        jbtadicao.setBackground(new java.awt.Color(0, 0, 0));
        jbtadicao.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtadicao.setForeground(new java.awt.Color(255, 255, 255));
        jbtadicao.setText("+");
        jbtadicao.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtadicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtadicaoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtadicao);

        jbtsinal.setBackground(new java.awt.Color(0, 0, 0));
        jbtsinal.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtsinal.setForeground(new java.awt.Color(255, 255, 255));
        jbtsinal.setText("+/-");
        jbtsinal.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtsinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtsinalActionPerformed(evt);
            }
        });
        jPanel1.add(jbtsinal);

        jbt0.setBackground(new java.awt.Color(0, 0, 0));
        jbt0.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbt0.setForeground(new java.awt.Color(255, 255, 255));
        jbt0.setText("0");
        jbt0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbt0ActionPerformed(evt);
            }
        });
        jPanel1.add(jbt0);

        jbtresultado.setBackground(new java.awt.Color(0, 0, 0));
        jbtresultado.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jbtresultado.setForeground(new java.awt.Color(255, 255, 255));
        jbtresultado.setText("=");
        jbtresultado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jbtresultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtresultadoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtresultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jfTela)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jfTela, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt0ActionPerformed
        jfTela.setText(jfTela.getText() + "0");
    }//GEN-LAST:event_jbt0ActionPerformed

    private void jbt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt1ActionPerformed
        jfTela.setText(jfTela.getText() + "1");
    }//GEN-LAST:event_jbt1ActionPerformed

    private void jbt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt2ActionPerformed
        jfTela.setText(jfTela.getText() + "2");
    }//GEN-LAST:event_jbt2ActionPerformed

    private void jbt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt3ActionPerformed
        jfTela.setText(jfTela.getText() + "3");
    }//GEN-LAST:event_jbt3ActionPerformed

    private void jbt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt4ActionPerformed
        jfTela.setText(jfTela.getText() + "4");
    }//GEN-LAST:event_jbt4ActionPerformed

    private void jbt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt5ActionPerformed
        jfTela.setText(jfTela.getText() + "5");
    }//GEN-LAST:event_jbt5ActionPerformed

    private void jbt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt6ActionPerformed
        jfTela.setText(jfTela.getText() + "6");
    }//GEN-LAST:event_jbt6ActionPerformed

    private void jbt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt7ActionPerformed
        jfTela.setText(jfTela.getText() + "7");
    }//GEN-LAST:event_jbt7ActionPerformed

    private void jbt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt8ActionPerformed
        jfTela.setText(jfTela.getText() + "8");
    }//GEN-LAST:event_jbt8ActionPerformed

    private void jbt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbt9ActionPerformed
        jfTela.setText(jfTela.getText() + "9");
    }//GEN-LAST:event_jbt9ActionPerformed

    private void jbtvirgulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtvirgulaActionPerformed
        jfTela.setText(jfTela.getText() + ",");
    }//GEN-LAST:event_jbtvirgulaActionPerformed

    private void jbtlimpatelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtlimpatelaActionPerformed
        jfTela.setText("");
    }//GEN-LAST:event_jbtlimpatelaActionPerformed

    private void jbtmultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtmultiplicacaoActionPerformed
        valor1 = Double.parseDouble(jfTela.getText());
        jfTela.setText("");
        operacao = "multiplicacao";
    }//GEN-LAST:event_jbtmultiplicacaoActionPerformed

    private void jbtquadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtquadradoActionPerformed
        valor1 = Double.parseDouble(jfTela.getText());
        operacao = "quadrado";
    }//GEN-LAST:event_jbtquadradoActionPerformed

    private void jbtadicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtadicaoActionPerformed
        valor1 = Double.parseDouble(jfTela.getText());
        jfTela.setText("");
        operacao = "soma";
    }//GEN-LAST:event_jbtadicaoActionPerformed

    private void jbtresultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtresultadoActionPerformed

        valor2 = Double.parseDouble(jfTela.getText());
        if (operacao == "soma") {
            jfTela.setText(String.valueOf(valor1 + valor2));
        }
        if (operacao == "subtracao") {
            jfTela.setText(String.valueOf(valor1 - valor2));
        }
        if (operacao == "multiplicacao") {
            jfTela.setText(String.valueOf(valor1 * valor2));
        }
        if (operacao == "divisao") {
            jfTela.setText(String.valueOf(valor1 / valor2));
        }
        if (operacao == "quadrado") {
            jfTela.setText(String.valueOf(valor1 * valor1));
        }

    }//GEN-LAST:event_jbtresultadoActionPerformed

    private void jbtsubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsubtracaoActionPerformed
        valor1 = Double.parseDouble(jfTela.getText());
        jfTela.setText("");
        operacao = "subtracao";
    }//GEN-LAST:event_jbtsubtracaoActionPerformed

    private void jbtdivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtdivisaoActionPerformed
        valor1 = Double.parseDouble(jfTela.getText());
        jfTela.setText("");
        operacao = "divisao";
    }//GEN-LAST:event_jbtdivisaoActionPerformed

    private void jbtsinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtsinalActionPerformed
        double ops = Double.parseDouble(String.valueOf(jfTela.getText()));
        ops = ops * (-1);
        jfTela.setText(String.valueOf(ops));
    }//GEN-LAST:event_jbtsinalActionPerformed

    private void jbtbackspaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtbackspaceActionPerformed
        String backspace = null;

        if (jfTela.getText().length() > 0) {
            StringBuilder strB = new StringBuilder(jfTela.getText());
            strB.deleteCharAt(jfTela.getText().length() - 1);
            backspace = strB.toString();
            jfTela.setText(backspace);
        }
    }//GEN-LAST:event_jbtbackspaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbt0;
    private javax.swing.JButton jbt1;
    private javax.swing.JButton jbt2;
    private javax.swing.JButton jbt3;
    private javax.swing.JButton jbt4;
    private javax.swing.JButton jbt5;
    private javax.swing.JButton jbt6;
    private javax.swing.JButton jbt7;
    private javax.swing.JButton jbt8;
    private javax.swing.JButton jbt9;
    private javax.swing.JButton jbtadicao;
    private javax.swing.JButton jbtbackspace;
    private javax.swing.JButton jbtdivisao;
    private javax.swing.JButton jbtlimpatela;
    private javax.swing.JButton jbtmultiplicacao;
    private javax.swing.JButton jbtquadrado;
    private javax.swing.JButton jbtresultado;
    private javax.swing.JButton jbtsinal;
    private javax.swing.JButton jbtsubtracao;
    private javax.swing.JTextField jfTela;
    // End of variables declaration//GEN-END:variables
}
